name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Download code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      # Build webapp
      - name: Build webapp
        run: npm install && npm run build && echo "iotawebwallet.com" > ./dist/CNAME

      # Upload webapp
      - name: Upload webapp
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true # Automatically remove deleted files from the deploy branch
